[theme]
primaryColor = "#1f77b4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "developer"

[server]
maxUploadSize = 500
enableXsrfProtection = true
headless = true

[logger]
level = "warning"
